<div class="nav-collapse collapse">
	<ul class="nav">
		<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
		<li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a></li>
		<li><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('User') ?></a></li>
		<li><a href="<?php echo $this->url('slider') ?>"><?php echo $this->translate('Slider') ?></a></li>
	</ul>
	<ul class="top-links nav">
	    	<li><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
		    <li><a href="javascript:void(0);"><?php echo $this->translate('Login') ?></a></li>
	</ul>
</div>