<?php echo $this->doctype(); ?>

<html lang="en">
    <?php echo $this->partial('partials/head.phtml'); ?>
    <body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a> <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
				<?php echo $this->partial('partials/nav.phtml')?>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<div class="container">
            <?php echo $this->content; ?>
            <hr>
            <?php echo $this->partial('partials/footer.phtml')?>
        </div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
