<section id="unseen">
<h2>Banner slider</h2>
<a href="<?php echo $this->url("slider/add")?>"><?php echo $this->translate("Add Slider")?></a>
<div class="table-responsive">
<table class="table-bordered table-striped table-condensed table">
	<thead>
		<tr>
			<th><?php echo $this->translate("Code")?></th>
			<th><?php echo $this->translate("Title")?></th>
			<th><?php echo $this->translate("Picture")?></th>
			<th><?php echo $this->translate("Order")?></th>
			<th class="numeric"><?php echo $this->translate("State")?></th>
			<th >Action</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>AAC</td>
			<td>AUSTRALIAN AGRICULTURAL COMPANY LIMITED.</td>
			<td class="numeric">$1.38</td>
			<td class="numeric">-0.01</td>
			<td class="numeric">-0.36%</td>
			<td >Action</td>
		</tr>
		<tr>
			<td>AAC</td>
			<td>AUSTRALIAN AGRICULTURAL COMPANY LIMITED.</td>
			<td class="numeric">$1.38</td>
			<td class="numeric">-0.01</td>
			<td class="numeric">-0.36%</td>
			<td >Action</td>
		</tr>
	</tbody>
</table>
</div>
</section>		    