<section id="unseen">
<h2>Banner slider</h2>
<a href="<?php echo $this->url("slider/add")?>"><?php echo $this->translate("Add Slider")?></a>
<div class="table-responsive">
<table class="table-bordered table-striped table-condensed table">
	<thead>
		<tr>
			<th style="width:5%;"><?php echo $this->translate("Code")?></th>
			<th style="width: 50%;"><?php echo $this->translate("Title")?></th>
			<th><?php echo $this->translate("Picture")?></th>
			<th><?php echo $this->translate("Order")?></th>
			<th class="numeric"><?php echo $this->translate("State")?></th>
			<th >Action</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	    $data = $this->data;
	if(count($data)>0):?>
	    <?php foreach ($data as $key => $v):?>
		<tr>
			<td class="t-code"><?php echo $v['id']?></td>
			<td><?php echo $v['title']?></td>
			<td class="numeric">$1.38</td>
			<td class="numeric"><?php echo $v["order"]?></td>
			<td class="numeric"><?php echo $v['state']?></td>
			<td >
			<a href="<?php echo $this->url("slider/default",array('action'=>'edit','controller'=>'index','id'=>$v['id']))?>">Edit</a>
			</td>
		</tr>
		<?php endforeach;?>
		<?php else: ?>
		<tr>
			<td colspan="6"><?php echo $this->translate("Data is empty")?></td>
		</tr>
		<?php endif; ?>
	</tbody>
</table>
</div>
</section>		    